from building import *

cwd     = GetCurrentDir()
src = []

if GetDepend(['PKGS_USING_LIBMODBUS_MAIN_RTU']):
    src += Glob('rtt_modbus_rtu.c')

CPPPATH = [cwd]

group = DefineGroup('libmodbus', src, depend = ['PKGS_USING_LIBMODBUS_MAIN'], CPPPATH = CPPPATH)

Return('group')
